@host = Host: 127.0.0.1:3000

###
GET /health_check
{{ host }}

###

POST /login
{{ host }}
Content-Type: application/json

{
    "username": "santi",
    "password": "pepe223"
}

###

POST /register
{{ host }}
Content-Type: application/json

{
    "username": "santi",
    "password": "pepe22"
}
###

GET /is_auth
Content-Type: application/json
{{ host }}
